---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
api.http.host: 0.0.0.0

node.name: logstash

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.elasticsearch.ssl:
  certificate_authority: /usr/share/logstash/config/certs/ca.crt
  verification_mode: full
  
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "${LOGSTASH_INTERNAL_PASSWORD}"
